accounts/urls.py
from accounts import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('logout', views.logout, name='logout')
]

contact/urls.py
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact')
]

home/urls.py
from home import views
from django.urls import path

app_name = 'all'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list', views.RestaurantList.as_view(), name='list'),
    path('create', views.CreateRestaurantView.as_view(), name='create'),
    path('search', views.search, name='search'),
    path('<slug:pk>', views.RestaurantDetailView.as_view(), name='detail'),
    path('update/<slug:pk>', views.RestaurantUpdateView.as_view(), name='update'),

]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contact/', include('contact.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    topic = models.CharField(max_length=300)
    message = models.TextField()

    def __str__(self):
        return self.name

home/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.utils.timezone import now

# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=300)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    website = models.URLField()
    phone_number = models.CharField(max_length=50, blank=True)
    date_added = models.DateField(default=now)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('all:detail', kwargs={'pk': self.pk})

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages,auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def register_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.error(request, message='Sorry. This email address already exists!')
            return redirect(to='accounts:register')
        else:
            user = User(username=username,first_name=first_name, last_name=last_name,
                        email=email, password=password)

            user.save()
            messages.success(request, message='You have been Registered successfully')
            return redirect(to='all:index')

    else:
        return render(request, 'accounts/register.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, 'You have been successfully logged in')
                return redirect(to='all:index')
            else:
                messages.error(request, message='This user is not Active')
                return redirect(to='accounts:login')
        else:
            messages.error(request, 'Invalid Login Details. Please Try again')
            return redirect(to='accounts:login')

    else:
        return render(request, 'accounts/login.html')


@login_required
def logout(request):
    auth.logout(request)
    return redirect(to='all:index')

contact/views.py
from django.shortcuts import render, redirect
from contact.models import Contact
from django.contrib import messages
from django.core.mail import send_mail


def contact(request):
    if request.method == 'POST':
        name = request.POST['name'],
        email = request.POST['email'],
        topic = request.POST['topic'],
        message = request.POST['message']

        contact = Contact(name=name, email=email, topic=topic, message=message)

        contact.save()

        send_mail(
            subject='New Contact Message',
            message='A contact message has been sent to you. Sign into the Admin Panel to see it ',
            from_email='emmandukwe26@gmail.com',
            recipient_list=['ellamoves01@gmail.com'],
            fail_silently=False,
        )

        messages.success(request, 'Your message has been successfully sent. We will get back to you soon.')
        return redirect(to='all:index')

    return render(request, 'contact/contact.html')

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from home.models import Restaurant


class IndexView(TemplateView):
    template_name = 'index.html'


class CreateRestaurantView(LoginRequiredMixin, CreateView):
    fields = ('name', 'address', 'city', 'state', 'website', 'phone_number')
    model = Restaurant
    template_name = 'home/add_restaurant.html'


class RestaurantList(ListView):
    context_object_name = 'restaurant_list'
    model = Restaurant
    template_name = 'home/restaurant_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Restaurant.objects.filter(is_published=True).order_by('-id')


class RestaurantDetailView(DetailView):
    context_object_name = 'restaurant_detail'
    model = Restaurant
    template_name = 'home/restaurant_detail.html'


class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    fields = ('name', 'address', 'city', 'state')
    template_name = 'home/restaurant_update.html'
    model = Restaurant


def search(request):
    # First query the database, and order and filter as you want
    queryset_list = Restaurant.objects.filter(is_published=True).order_by('-date_added')

    # Look for the model entry 'name' in the database, get it and filter it to be exactly as inputted in the form
    if 'name' in request.GET:
        name = request.GET['name']
        if name:
            # Django field lookups
            queryset_list = queryset_list.filter(name__iexact=name)

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact=state)

    context = {
        'restaurant': queryset_list,
    }
    return render(request, 'home/search.html', context=context)

templates/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="container" id="message">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button class="close" type="button" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags| title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} | Login {% endblock %}
{% include '_alerts.html' %}
{% block content %}
<section class="register-section">
    <h3 class="form-title"><strong>LOGIN</strong></h3>
    <hr>
    <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <button type="submit" class="btn btn-success">Login</button>
    </form>
</section>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} | Register {% endblock %}
{% include '_alerts.html' %}
{% block content %}

<section class="register-section">
    <h3 class="form-title"><strong>REGISTER</strong></h3>
    <hr>
    <form method="POST" action="{% url 'accounts:register' %}">
            {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">First Name</label>
                    <input type="text" class="form-control" name="first_name">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">Last Name</label>
                    <input type="text" class="form-control" name="last_name">
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Email Address</label>
            <input type="email" class="form-control" name="email">
        </div>
        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <button type="submit" class="btn btn-success">Register</button>
    </form>
</section>

{% endblock %}

templates/base.html
<!doctype html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!--    Bootstrap Css-->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!--    Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Red+Hat+Display&family=Roboto&display=swap" rel="stylesheet">
<!--    Custom Css-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Restaurant Public Database {% block title %} {% endblock %}</title>
</head>
<body>
<!--Navbar Section-->
<section id="navigation-bar">
    <nav class="navbar navbar-expand-lg my_navbar">
        <div class="container-fluid d-flex">
            <img src="{% static 'logo.png' %}" alt="Restaurant database logo" class="logo">
            <a class="navbar-brand nav-brand" href="">ResDB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-row-reverse" id="navbarText">
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'all:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'contact:contact' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'all:list' %}">All Restaurants</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'all:search' %}">Search Restaurant</a>
                    </li>
                    {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'all:create' %}">Add Restaurant</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
                     </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</section>
        {% block content %}


        {% endblock %}
<!--Bootstrap Javascript-->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/contact/contact.html
{% extends 'base.html' %}
{% block title %} | Contact {% endblock %}
{% block content %}
<section class="register-section">
    <h3 class="form-title"><strong>SEND US A MESSAGE</strong></h3>
    <hr>
    <form method="POST" action="{% url 'contact:contact' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="mb-3">
            <label class="form-label">Email Address</label>
            <input type="email" class="form-control" name="email">
        </div>
        <div class="mb-3">
            <label class="form-label">Topic</label>
            <input type="text" class="form-control" name="topic">
        </div>
        <div class="mb-3">
             <label class="form-label">Write your Message Here</label>
           <textarea cols="100" rows="7" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Contact</button>
    </form>
</section>

{% endblock %}

templates/home/add_restaurant.html
{% extends 'base.html' %}
{% block title %} | Add Restaurant {% endblock %}
{% block content %}
<section class="register-section">
    <h3 class="form-title"><strong>ADD A NEW RESTAURANT</strong></h3>
    <hr>
    <form method="POST" action="{% url 'all:create' %}">
        {%  csrf_token %}
        <div class="mb-3">
            <label class="form-label">Restaurant Name</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="mb-3">
            <label class="form-label">Address</label>
            <input type="text" class="form-control" name="address">
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">City</label>
                    <input type="text" class="form-control" name="city">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">State</label>
                    <input type="text" class="form-control" name="state">
                </div>
            </div>
        </div>
         <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">Website</label>
                    <input type="url" class="form-control" name="website">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label class="form-label">Phone Number</label>
                    <input type="text" class="form-control" name="phone_number">
                </div>
            </div>
        </div>
<!--        <div class="mb-3">-->
<!--            <label class="form-label">Additional Comments</label>-->
<!--            <textarea name="comments" cols="70" rows="7"></textarea>-->
<!--        </div>-->
        <button type="submit" class="btn btn-success">Add Restaurant</button>
    </form>
</section>

{% endblock %}

templates/home/restaurant_detail.html
{% extends 'base.html' %}
{% block title %} | Detail {% endblock %}
{% block content %}
<section class="restaurant_list_body">
    <h1 class="title"><strong>Welcome to {{ restaurant_detail.name }} detail page</strong></h1>
    <hr>
    <p class="detail_paragraph">Name: {{ restaurant_detail.name }}</p>
    <p class="detail_paragraph">Address: {{ restaurant_detail.address }}</p>
    <p class="detail_paragraph">City: {{ restaurant_detail.city }}</p>
    <p class="detail_paragraph">State: {{ restaurant_detail.state }}</p>
    <p class="detail_paragraph">Website: <a href="{{ restaurant_detail.website }}">{{ restaurant_detail.name }}</a></p>
    <p class="detail_paragraph">Phone Number: {{ restaurant_detail.phone_number }}</p>
    <p class="detail_paragraph">Date Added: {{ restaurant_detail.date_added }}</p>
    {% if user.is_authenticated %}
    <div class="new_restaurant">
        <a href="{% url 'all:update' pk=restaurant_detail.pk %}"> <input type="submit" value="Update" class="btn btn-success"></a>
    </div>
    {% else %}

    {% endif %}
</section>



{% endblock %}

templates/home/restaurant_list.html
{% extends 'base.html' %}
{% block title %} | Restaurant List {% endblock %}
{% block content %}
<section class="restaurant_list_body">
    <h1 class="title"><strong>All Recorded Restaurants</strong></h1>
    <hr>

    <table class="table table-striped table-hover">
        <div class="table-content">
            <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Name</th>
                <th scope="col">Address</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Website</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Date Added</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>

                {% for restaurant in restaurant_list %}
                <tr>
                    <th scope="row">{{ restaurant.id }}</th>
                    <td>{{ restaurant.name }}</td>
                    <td>{{ restaurant.address }}</td>
                    <td>{{ restaurant.city }}</td>
                    <td>{{ restaurant.state }}</td>
                    <td><a href="{{ restaurant.website }}">{{ restaurant.name }}</a></td>
                    <td>{{ restaurant.phone_number }}</td>
                    <td>{{ restaurant.date_added }}</td>
                    <td><a href="{{ restaurant.id }}"><input type="submit" value="View" class="btn btn-success"></a></td>
                    {% if user.is_authenticated %}
                    <td><a href="{% url 'all:update' pk=restaurant.pk %}"><input type="submit" value="Update" class="btn btn-warning"></a></td>
                    {% else %}

                    {% endif %}

                </tr>
                {% endfor %}

            </tbody>
        </div>
    </table>
    <nav aria-label="Page navigation example">
    <div class="pagination">
         {% if page_obj.has_other_pages %}
            <ul class="pagination">
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&laquo;</a>
                </li>
              {% endif %}
              {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="page-item active">
                    <a class="page-link">{{ i }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item">
                  <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
    </div>
</nav>
    {% if user.is_authenticated %}
    <div class="new_restaurant">
        <a href="{% url 'all:create' %}"> <input type="submit" value="Add New Restaurant" class="btn btn-success"></a>
    </div>

    {% endif %}
 </section>

{% endblock %}

templates/home/restaurant_update.html
{% extends 'base.html' %}
{% block title %} | Update Restaurant{% endblock %}
{% block content %}
    <section class="restaurant_list_body">
        <h1 class="title">Update {{ restaurant.name }}</h1>
        <hr>
        <form method="POST">
            {% csrf_token %}
             <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="mb-3">
                <label class="form-label">Address</label>
                <input type="text" class="form-control" name="address">
            </div>
           <div class="row">
               <div class="col">
                    <div class="mb-3">
                        <label class="form-label">City</label>
                        <input type="text" class="form-control" name="city">
                    </div>
               </div>
               <div class="col">
                   <div class="mb-3">
                        <label class="form-label">State</label>
                        <input type="text" class="form-control" name="state">
                    </div>
               </div>
           </div>

            <div class="new_restaurant">
                <input type="submit" class="btn btn-success" value="submit">
            </div>
        </form>

    </section>

{% endblock %}

templates/home/search.html
{% extends 'base.html' %}
{% block title %} | Search {% endblock %}
{% block content %}
    <section id="search_section">
    <div class="container-fluid">
        <form action="{% url 'all:search' %}">
            <div class="row align-items-center">
                <div class="col-md-4 mb-3" style="margin:0 35%;">
                    <label class="form-label">Restaurant Name</label>
                    <input type="text" class="form-control" name="restaurant_name" placeholder="Restaurant Name">
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-3" style="margin:0 5% 0 15%;">
                    <label class="form-label">City</label>
                    <input type="text" class="form-control" name="city" placeholder="City e.g. Port Harcourt">
                </div>
                <div class="col-md-4 mb-3" style="margin:0 3% 0 5%;">
                    <label class="form-label">State</label>
                    <input type="text" class="form-control" name="state" placeholder="State e.g. Rivers State">
                </div>
            </div>
           <div class="search_button" style="padding:0 45%;">
                <button class="btn btn-success btn-block mt-4" type="submit">Search</button>
           </div>
        </form>
    </div>
</section>

<section class="restaurant_list_body">
    {% if restaurant %}
    <h1 class="title"><strong>Search Results</strong></h1>
    <hr>

    <table class="table table-striped table-hover">
        <div class="table-content">
            <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Name</th>
                <th scope="col">Address</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Website</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Date Added</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
                {% for restaurant in restaurant %}
                <tr>
                    <th scope="row">{{ restaurant.id }}</th>
                    <td>{{ restaurant.name }}</td>
                    <td>{{ restaurant.address }}</td>
                    <td>{{ restaurant.city }}</td>
                    <td>{{ restaurant.state }}</td>
                    <td><a href="{{ restaurant.website }}">{{ restaurant.name }}</a></td>
                    <td>{{ restaurant.phone_number }}</td>
                    <td>{{ restaurant.date_added }}</td>
                    <td><a href="{{ restaurant.id }}"><input type="submit" value="View" class="btn btn-success"></a></td>
                    {% if user.is_authenticated %}
                    <td><a href="{% url 'all:update' pk=restaurant.pk %}"><input type="submit" value="Update" class="btn btn-warning"></a></td>
                    {% else %}

                    {% endif %}

                </tr>
                {% endfor %}
                 {% else %}
                 <h3>No Restaurants Available</h3>
            {% endif %}

            </tbody>
        </div>
    </table>
 </section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %} | Find Restaurant {% endblock %}
{% block content %}
{% include '_alerts.html' %}
    <section id="homepage-section">
        <h1 class="title"><strong>Find Restaurants Near You!!</strong></h1>
            <p class="content-body">
                A Database of Restaurants in Nigeria.
                Add restaurants you love, leave a comment, and more!
            </p>
        <div class="home-button-div">
            <a href="{% url 'all:list' %}"><input type="submit" class="btn btn-lg home-button" value="All Restaurants"></a>
        </div>
    </section>

{% endblock %}